name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - conda
  - pip
  - setuptools==61.3.1
  - tqdm
  - numpy
  - pandas
  - matplotlib
  - jupyterlab==3.3.3
  - ipywidgets==7.7.0
